### ISSUE TITLE
ftp_nlist(): php_connect_nonb() failed

### ISSUE THREAD

**Issue by AkramiPro** [lazzard/php-ftp-client#35] opened 2022-04-02 12:29 UTC
[FtpClientException] - ftp_nlist(): php_connect_nonb() failed: Operation now in progress (115)

i try passive mode on/off & SSL off/on but did not work

**Comment by AmraniCh** [comment] 2022-04-10 22:30
Hey, thanks for opening this issue.

Are you sure you've enabled the passive mode ?

If you enabled the passive mode and the error still exist, I suggest using this tool [Lazzard\Ftpbridge](https://github.com/lazzard/ftp-bridge) to know what the exact error message sent from the server, just use the example usage, and share the logs here (do not forget to hide the username and the password in the generated logs).

**Comment by tuyenlaptrinh** [comment] 2022-12-27 04:41
Same error and this is error when use FTPBridge
```
Failed to establish a successful passive data connection to the (xx.xx.xx.xx) : stream_socket_client(): unable to connect to tcp://xx.xx.xx.xx:35892
```

**Comment by AmraniCh** [comment] 2022-12-27 08:07
@tuyenlaptrinh have you used the logger ? can you paste the logs here please ?

**Comment by tuyenlaptrinh** [comment] 2022-12-27 08:23
Hi @AmraniCh
I used "Usage Example" in your github repository FTPBridge and I only got that error with no log

**Comment by AmraniCh** [comment] 2023-05-07 10:04
I will close this issue as long as the error is not caused by the library implementation, some FTP servers may have an incorrect configuration of file transfer operations (active/passive transfers), so I suggest having contact with your server administrator, thanks!

**Closed by AmraniCh** 2023-05-07 10:04 UTC
